# Generated by Django 5.2.4 on 2025-07-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_department_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/'),
        ),
    ]
