# Generated by Django 5.2.4 on 2025-07-18 07:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_master_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='contact',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Contact number must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
    ]
