# Generated by Django 5.2.4 on 2025-07-23 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0007_attendancelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancelog',
            name='time_out',
        ),
    ]
