# Generated by Django 5.2.4 on 2025-07-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0008_remove_attendancelog_time_out'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancelog',
            old_name='time_in',
            new_name='time',
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='event',
            field=models.CharField(default='Repeat', max_length=20),
        ),
    ]
